feat: add conventional commit standard

diff --git a/.husky/commit-msg b/.husky/commit-msg
--- a/.husky/commit-msg
+++ b/.husky/commit-msg
@@ -3,7 +3,7 @@
 echo 'Husky - [Commit Msg]:'
 
 if ! head -1 "$1" | grep -qE "^(feat|fix|ci|chore|style|test|refactor|perf|build|revert)(\(.+?\))?: .{1,}$"; then
-  echo "Aborting commit. Your commit message format is invalid." >&2
+  echo "Aborting commit. Your commit message format is invalid, look at https://www.conventionalcommits.org/" >&2
   exit 1
 fi
 if ! head -1 "$1" | grep -qE "^.{1,88}"; then
